# file: roles/nginx/tasks/modules/http_stub_status_module.yml

# flag: --with-http_stub_status_module

- include: _authorized_ips.yml

- name: Make sure the nginx status configuration is updated
  template: src=../../../templates/modules/nginx.status.j2 dest={{ nginx_dir }}/sites-available/nginx_status owner=root group=root mode=0644
  sudo: yes

- name: Enable the status stub site
  file: path={{ nginx_dir }}/sites-enabled/nginx_status src={{ nginx_dir }}/sites-available/nginx_status state=link
  sudo: yes
