# file: roles/kafka/tasks/user.yml

- name: Kafka | Make sure the kafka group is present
  action: group gid=$kafka_gid name=$kafka_group state=present

- name: Kafka | Make sure the kafka user directory is present
  action: file path="/app/home/$kafka_user" state=directory

- name: Kafka | Make sure the kafka user is present
  user: uid=$kafka_uid name=$kafka_user group=$kafka_group home="/app/home/$kafka_user" shell=/bin/bash state=present comment="Kafka user"

- name: Kafka | Set the right kafka user directory permissions
  action: file path="/app/home/$kafka_user" owner=$kafka_user group=$kafka_group mode=0700 state=directory

- name: Kafka | Set the right expiration on the kafka user
  command: "sudo chage -I -1 -E -1 -m -1 -M -1 -W -1 -E -1 $kafka_user"
