# file: roles/scale/tasks/main.yml

- name: Scala | Download Scala
  command: wget http://www.scala-lang.org/files/archive/scala-$scala_version_download.tgz chdir=/tmp creates=/tmp/scala-$scala_version_download.tgz

- name: Scala | Unpack the compressed Scala binaries
  command: tar -xvzf /tmp/scala-$scala_version_download.tgz chdir=/usr/local/java creates=/usr/local/java/scala-$scala_version_download

- name: Scala | Set the permissions on the Scala binaries
  file: path=/usr/local/java/scala-$scala_version_download/bin state=directory mode=0755 recurse=yes

- name: Scala | Update the symbolic link to the Scala install
  file: path=/usr/local/java/scala src=/usr/local/java/scala-$scala_version_download state=link force=yes

- name: Scala | Add the Scala binary to the system path (/etc/profile)
  lineinfile: $item
  with_items:
  - dest=/etc/profile regexp='^SCALA_HOME=/usr/local/java/scala' line="SCALA_HOME=/usr/local/java/scala" state=present
  - dest=/etc/profile regexp='^PATH=.*SCALA_HOME.*' line="PATH=$PATH:$SCALA_HOME/bin" state=present

- name: Scala | Inform the system where Scala is located
  command: $item
  with_items:
    - update-alternatives --install "/usr/bin/scala" "scala" "/usr/local/java/scala/bin/scala" 1
    - update-alternatives --install "/usr/bin/scalac" "scalac" "/usr/local/java/scala/bin/scalac" 1
    - update-alternatives --install "/usr/bin/scalap" "scalap" "/usr/local/java/scala/bin/scalap" 1

- name: Scala | Set the system default for Scala
  command: $item
  with_items:
    - update-alternatives --set scala /usr/local/java/scala/bin/scala
    - update-alternatives --set scalac /usr/local/java/scala/bin/scalac
    - update-alternatives --set scalap /usr/local/java/scala/bin/scalap
