# file: roles/fileserver/main.yml

- name: Netatalk | Make sure netatalk is installed
  apt: pkg=netatalk state=installed

- name: Netatalk | Make sure the shared directory exists
  action: group gid=9999 name=shared

- name: Netatalk | Make sure the shared group exists
  file: path=/srv/data/shared state=directory owner=root group=shared mode=0775

- name: Netatalk | Update the netatalk configuration
  copy: {{ item }}
  with_items:
    - src=etc_default_netatalk dest=/etc/default/netatalk owner=root group=root mode=0644
    - src=etc_netatalk_AppleVolumes.default dest=/etc/netatalk/AppleVolumes.default owner=root group=root mode=0644
    - src=etc_netatalk_afpd.conf dest=/etc/netatalk/afpd.conf owner=root group=root mode=0644
  notify:
    - restart netatalk
