# file: roles/storm/tasks/supervise_nimbus.yml

- name: Storm | Install the supervisord storm-nimbus script
  template: src=etc_supervisor.d_storm-nimbus.conf.j2 dest=/etc/supervisor.d/storm-nimbus.conf owner=root group=root mode=0644
  notify:
    - restart supervisor

- name: Storm | Install the supervisord storm-ui script
  template: src=etc_supervisor.d_storm-ui.conf.j2 dest=/etc/supervisor.d/storm-ui.conf owner=root group=root mode=0644
  notify:
    - restart supervisor
