# file: roles/elasticsearch/tasks/supervise_cassandra.yml

- name: Install the supervisord elasticsearch script
  template: src=etc_supervisor.d_elasticsearch.conf.j2 dest=/etc/supervisor.d/elasticsearch.conf owner=root group=root mode=0644
  notify:
    - restart supervisor
