# file: roles/znc/tasks/install.yml

- name: ZNC | Install znc dependencies
  apt: pkg=$item state=installed
  with_items: $znc_dependencies

- name: ZNC | Download the znc source tarball
  get_url: url=http://znc.in/releases/znc-${znc_version}.tar.gz dest=/tmp/znc-${znc_version}.tar.gz

- name: ZNC | Unpack the znc source tarball
  command: tar xzf /tmp/znc-${znc_version}.tar.gz chdir=/tmp creates=/tmp/znc-${znc_version}/configure

- name: ZNC | Configure/make/make install znc
  shell: ./configure --enable-python ; make ; make install executable=/bin/bash chdir=/tmp/znc-${znc_version} creates=/usr/local/bin/znc

- name: ZNC | Copy the znc upstart script (/etc/init.d/znc)
  template: src=etc_init.d_znc.j2 dest=/etc/init.d/znc owner=root group=root mode=0755

- name: ZNC | Make sure the config folder is present
  file: path=/app/home/$znc_user/configs owner=znc group=znc state=directory

- name: ZNC | Update the znc configuration
  template: src=znc.conf.j2 dest=/app/home/$znc_user/configs/znc.conf owner=znc group=znc

- name: ZNC | Make sure znc is a system service and starts on startup
  command: update-rc.d znc defaults
  notify:
    - restart znc
